### PR TITLE
Fixes #8, #3

### LINKED ISSUE #8: Update the README with the instructions to start the Front End
Recently, the react boilerplate has been added. 
Add the instructions in the main README to start the front end

### PR DESCRIPTION
**Pull request by vipulbhj**
Explains separation between frontend and backend

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@vipulbhj , please resolve the conflicts :')

**Comment by vipulbhj** [comment]
It isn't showing me any conflicts :(

**Comment by vipulbhj** [comment]
Done, please check now

**Comment by stealthanthrax** [comment]
@vipulbhj , issue #15 is still open and not been fixed. I believe you tagged the wrong issue.

**Pull request merged**
